# Generated by Django 4.2.16 on 2024-11-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusdetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=20, null=True)),
                ('staff', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusstaffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('staffid', models.CharField(blank=True, max_length=10, null=True)),
                ('route', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='guardiantable',
            old_name='guardianid',
            new_name='studentname',
        ),
        migrations.RenameField(
            model_name='routetable',
            old_name='monthlycharges',
            new_name='tripno',
        ),
        migrations.RemoveField(
            model_name='stationtable',
            name='status',
        ),
        migrations.AddField(
            model_name='stationtable',
            name='charges',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='ph_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
