# Generated by Django 4.2.16 on 2024-11-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_busdetailstable_busstafftable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='busno',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='commuter_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
