# Generated by Django 4.2.16 on 2024-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_studenttable_busno_studenttable_commuter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='busroute',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='vehicleno',
            new_name='vehicle_number',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
