# Generated by Django 4.2.16 on 2024-11-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_busroute_studenttable_route_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='transpotation',
            new_name='transportation_type',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='presentstay',
        ),
    ]
