# Generated by Django 4.2.16 on 2024-11-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_studenttable_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='vehicle_type',
        ),
    ]
