# Generated by Django 4.2.17 on 2024-12-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_addstudenttable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetailstable',
            name='capacity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busdetailstable',
            name='station',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
