# Generated by Django 4.2.17 on 2024-12-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_busdetailstable_capacity_busdetailstable_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdetailstable',
            name='staff',
        ),
    ]
