# Generated by Django 4.2.17 on 2024-12-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_remove_busdetailstable_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetailstable',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.routetable'),
        ),
        migrations.AlterField(
            model_name='busdetailstable',
            name='vehicleno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
