# Generated by Django 4.2.17 on 2024-12-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_busdetailstable_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetailstable',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.routetable'),
        ),
    ]
