# Generated by Django 4.2.17 on 2024-12-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_alter_busdetailstable_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetailstable',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
