# Generated by Django 4.2.17 on 2024-12-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_busdetailstable_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('mode', models.CharField(max_length=50)),
                ('STATION', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.stationtable')),
                ('STUDENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.addstudenttable')),
            ],
        ),
    ]
