# Generated by Django 4.2.17 on 2024-12-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_paymenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='route',
        ),
        migrations.CreateModel(
            name='LabattendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrytime', models.DateTimeField(blank=True, null=True)),
                ('exittime', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('LAB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.labtable')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='GateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entrytime', models.DateTimeField(blank=True, null=True)),
                ('exittime', models.DateTimeField(blank=True, null=True)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='BusattendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entrytime', models.DateTimeField(blank=True, null=True)),
                ('exittime', models.DateTimeField(blank=True, null=True)),
                ('STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.stationtable')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.studenttable')),
            ],
        ),
    ]
