# Generated by Django 4.2.16 on 2024-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('INSTITUTE', 'Institute'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
