# Generated by Django 4.2.17 on 2024-12-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('INSTITUTE', 'Institute')], max_length=20),
        ),
    ]
