# Generated by Django 4.2.17 on 2024-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0021_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('INSTITUTE', 'Institute'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
